### ISSUE TITLE
Take some default metadata from starphleet env

### ISSUE THREAD

**Issue by shawnrushefsky** [glg/node-logger#1]
It would be cool if we injected some starphleet info into metadata automatically, based on environment variables.

For instance:

`MOUNTED_AT === ORDERS_NAME`

**Comment by ambroselittle** [comment]
Yeah, thinking as much potentially relevant Starphleet config:
* STARPHLEET_URL
* ORDERS_NAME
* SECURITY_MODE 

For example.. maybe also if we can get it the current container ID with the SHA values. 

Just some initial thoughts..

**Comment by drhayes** [comment]
GDS obviates most of this: FQDN is in orders, sourceCategory in sumo defines where it's deployed, cluster name is the `SECURITY_MODE`, etc.
